'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Cargos
    
    '''<summary>
    '''MenuBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Btn_Nuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Nuevo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Btn_Editar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Editar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Btn_Eliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Eliminar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''MenuSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuSelect As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LabelMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMatricula As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextMatricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNombre As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextNombre As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelCURP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCURP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextCurp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextCurp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_Buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Buscar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Btn_Limpiar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Limpiar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''GvAlumnos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GvAlumnos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''hdfValorGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfValorGrid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As CapaPresentacion.MasterDefault
        Get
            Return CType(MyBase.Master,CapaPresentacion.MasterDefault)
        End Get
    End Property
End Class
