'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ListEmpresa
    
    '''<summary>
    '''btn_Nuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Nuevo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''LabelRFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelRFC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Text_Rfc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text_Rfc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelRazonSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelRazonSocial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_Limpiar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Limpiar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btn_Buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Buscar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''gvEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEmpresa As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As CapaPresentacion.MasterDefault
        Get
            Return CType(MyBase.Master,CapaPresentacion.MasterDefault)
        End Get
    End Property
End Class
