'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ListPagos
    
    '''<summary>
    '''LabelMatricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelMatricula As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Text_Matricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text_Matricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelTutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelTutor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Text_Tutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text_Tutor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelRazonSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelRazonSocial As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Text_RazonSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text_RazonSocial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LabelNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNombre As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Text_NombreAlumno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Text_NombreAlumno As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_Limpiar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Limpiar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btn_Buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Buscar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gdvPagos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvPagos As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As CapaPresentacion.MasterDefault
        Get
            Return CType(MyBase.Master,CapaPresentacion.MasterDefault)
        End Get
    End Property
End Class
