'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class catAspirante
    Public Property IdAspirante As Integer
    Public Property Nombre_Aspirante As String
    Public Property Direccion_Aspirante As String
    Public Property Telefono_Aspirante As String
    Public Property Movil_Aspirante As String
    Public Property RFC_Aspirante As String
    Public Property FechaNacimiento_Aspirante As String
    Public Property eMail_Aspirante As String
    Public Property Sexo_Aspirante As Nullable(Of Integer)
    Public Property IDOcupacion As Nullable(Of Integer)
    Public Property Imagen As Byte()
    Public Property ContentType As String

End Class
