'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class catCausante
    Public Property IDCausante As Integer
    Public Property IDGimnasio As Integer
    Public Property RazonSocial As String
    Public Property Direccion As String
    Public Property Colonia As String
    Public Property Localidad As String
    Public Property Municipio As String
    Public Property CPostal As String
    Public Property RFC As String
    Public Property Telefono As String
    Public Property Tarjeta As Nullable(Of Integer)
    Public Property Estatus As Nullable(Of Integer)
    Public Property Iva As Nullable(Of Integer)
    Public Property CuentaIva As String
    Public Property IDMunicipio As Nullable(Of Integer)
    Public Property IDColonia As Nullable(Of Integer)
    Public Property CorreoElectronico As String
    Public Property Regimen As String
    Public Property SerieFactura As String

End Class
