'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class catCliente
    Public Property IDCliente As Integer
    Public Property IDGimnasio As Integer
    Public Property Nombre As String
    Public Property Direccion As String
    Public Property IDColonia As String
    Public Property Localidad As String
    Public Property IDMunicipio As String
    Public Property Estado As String
    Public Property CPostal As String
    Public Property Telefono As String
    Public Property MovilCelular As String
    Public Property MovilRadio As String
    Public Property RFC As String
    Public Property FechaAlta As String
    Public Property FechaNacimiento As String
    Public Property FechaUltimoPago As String
    Public Property FechaVencimiento As String
    Public Property Ocupacion As String
    Public Property eMail As String
    Public Property Sexo As Nullable(Of Integer)
    Public Property FechaUltimaAsistencia As String
    Public Property IDEmpresa As Nullable(Of Integer)
    Public Property NombreEmpresa As String
    Public Property Estatus As Nullable(Of Integer)
    Public Property FechaPenultimoPago As String
    Public Property Enviado As Nullable(Of Integer)
    Public Property IDOcupacion As String
    Public Property NumEmpleado As String
    Public Property Puesto As String
    Public Property Contrasena As String
    Public Property FechaPenultimoVencimiento As String
    Public Property IDProducto As Nullable(Of Integer)
    Public Property TipoCuota As Nullable(Of Integer)
    Public Property IDHuella As Nullable(Of Integer)
    Public Property Saldo As Nullable(Of Decimal)
    Public Property Imagen As Byte()

End Class
