'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class catEmpresa
    Public Property IDEmpresa As Integer
    Public Property RazonSocial As String
    Public Property Nombre As String
    Public Property Direccion As String
    Public Property Colonia As String
    Public Property Localidad As String
    Public Property Municipio As String
    Public Property CPostal As String
    Public Property RFC As String
    Public Property Telefono As String
    Public Property NombreContacto As String
    Public Property eMailContacto As String
    Public Property WebSite As String
    Public Property CelularContacto As String
    Public Property RadioContacto As String
    Public Property TelefonoContacto As String
    Public Property Extension As String
    Public Property Puesto As String
    Public Property Estatus As Nullable(Of Integer)
    Public Property IDMunicipio As String
    Public Property IDColonia As String
    Public Property Estado As String

End Class
