'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class catGimnasio
    Public Property IDGimnasio As Integer
    Public Property Nombre As String
    Public Property Estatus As Nullable(Of Integer)
    Public Property IDZonaGeografica As Nullable(Of Integer)
    Public Property NombreCorto As String
    Public Property PrefijoFolio As String
    Public Property NombreSucursal As String
    Public Property Compania As String
    Public Property Direccion As String
    Public Property RFC As String
    Public Property Regimen As String
    Public Property RazonSocial As String

End Class
