'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class catProveedore
    Public Property IDProveedor As Integer
    Public Property RazonSocial As String
    Public Property Direccion As String
    Public Property IDMunicipio As Nullable(Of Integer)
    Public Property IDColonia As Nullable(Of Integer)
    Public Property Localidad As String
    Public Property CPostal As String
    Public Property RFC As String
    Public Property Telefono As String
    Public Property WebSite As String
    Public Property Estatus As Nullable(Of Integer)
    Public Property NombreContacto As String
    Public Property PuestoContacto As String
    Public Property TelefonoContacto As String
    Public Property MovilContacto As String
    Public Property RadioContacto As String
    Public Property ExtContacto As String
    Public Property eMailContacto As String

End Class
