'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class catProducto
    Public Property IDProducto As Integer
    Public Property IDGimnasio As Nullable(Of Integer)
    Public Property Descripcion As String
    Public Property PrecioVenta As String
    Public Property Dias As Nullable(Of Integer)
    Public Property IDTipo As Integer
    Public Property ExistenciaInvFisico As Nullable(Of Integer)
    Public Property FechaInvFisico As String
    Public Property HInvFisico As String
    Public Property FUltimaCompra As String
    Public Property Existencia As Nullable(Of Integer)
    Public Property Estatus As Nullable(Of Integer)
    Public Property FactorIva As Nullable(Of Integer)
    Public Property CtaContable As String
    Public Property IDProveedor As Nullable(Of Integer)
    Public Property FechaBaja As String
    Public Property SeDescarga As Nullable(Of Integer)
    Public Property FUltimaVenta As String
    Public Property TipoCuota As Nullable(Of Integer)
    Public Property EnPlazos As Nullable(Of Integer)
    Public Property IDCategoria As Nullable(Of Integer)
    Public Property Imagen As Byte()

End Class
