'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class eimagenn_gym_0001
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=eimagenn_gym_0001")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property catAspirantes() As DbSet(Of catAspirante)
    Public Overridable Property catClientes() As DbSet(Of catCliente)
    Public Overridable Property catPlantillas() As DbSet(Of catPlantilla)
    Public Overridable Property catProveedores() As DbSet(Of catProveedore)
    Public Overridable Property tblAsistencias() As DbSet(Of tblAsistencia)
    Public Overridable Property tblEventos() As DbSet(Of tblEvento)
    Public Overridable Property tblEventosRapidos() As DbSet(Of tblEventosRapido)
    Public Overridable Property tblMovimientoCajas() As DbSet(Of tblMovimientoCaja)
    Public Overridable Property catCategorias() As DbSet(Of catCategoria)
    Public Overridable Property catCausantes() As DbSet(Of catCausante)
    Public Overridable Property catColonias() As DbSet(Of catColonia)
    Public Overridable Property catEmpleados() As DbSet(Of catEmpleado)
    Public Overridable Property catEmpresas() As DbSet(Of catEmpresa)
    Public Overridable Property catEstados() As DbSet(Of catEstado)
    Public Overridable Property catGimnasios() As DbSet(Of catGimnasio)
    Public Overridable Property catMunicipios() As DbSet(Of catMunicipio)
    Public Overridable Property catOcupaciones() As DbSet(Of catOcupacione)
    Public Overridable Property catProductos() As DbSet(Of catProducto)
    Public Overridable Property catUsuarios() As DbSet(Of catUsuario)
    Public Overridable Property catZonaGeograficas() As DbSet(Of catZonaGeografica)
    Public Overridable Property tblAsistencia1() As DbSet(Of tblAsistencia1)
    Public Overridable Property tblDetalleventas() As DbSet(Of tblDetalleventa)
    Public Overridable Property tblFoliosVentas() As DbSet(Of tblFoliosVenta)
    Public Overridable Property tblProductoPrecios() As DbSet(Of tblProductoPrecio)
    Public Overridable Property v_Asistencia() As DbSet(Of v_Asistencia)
    Public Overridable Property v_AsistenciaCliente() As DbSet(Of v_AsistenciaCliente)
    Public Overridable Property v_AsistenciaHombreMujer() As DbSet(Of v_AsistenciaHombreMujer)
    Public Overridable Property v_AsistXHora() As DbSet(Of v_AsistXHora)
    Public Overridable Property v_AsisVencidas() As DbSet(Of v_AsisVencidas)
    Public Overridable Property v_CantProdPorFecha() As DbSet(Of v_CantProdPorFecha)
    Public Overridable Property v_CantProdPorFechaGimnasio() As DbSet(Of v_CantProdPorFechaGimnasio)
    Public Overridable Property v_CompraProveedor() As DbSet(Of v_CompraProveedor)
    Public Overridable Property v_ComprasXProducto() As DbSet(Of v_ComprasXProducto)
    Public Overridable Property v_Empleados() As DbSet(Of v_Empleados)
    Public Overridable Property v_EstAsisXCliente() As DbSet(Of v_EstAsisXCliente)
    Public Overridable Property v_FolioDesgloce() As DbSet(Of v_FolioDesgloce)
    Public Overridable Property v_FolioDesgloceGimnasio() As DbSet(Of v_FolioDesgloceGimnasio)
    Public Overridable Property v_KardexProductos() As DbSet(Of v_KardexProductos)
    Public Overridable Property v_prueba() As DbSet(Of v_prueba)
    Public Overridable Property v_Test() As DbSet(Of v_Test)
    Public Overridable Property v_VentasxProdHist() As DbSet(Of v_VentasxProdHist)
    Public Overridable Property v_VentasXProducto() As DbSet(Of v_VentasXProducto)
    Public Overridable Property v_VtasGral() As DbSet(Of v_VtasGral)

End Class
