'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblAsistencia1
    Public Property IDGimnasio As Integer
    Public Property IDGimnasio2 As Integer
    Public Property IDCliente As Integer
    Public Property Fecha As String
    Public Property Hora As String
    Public Property Enviado As Nullable(Of Integer)

End Class
