'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblDetalleventa
    Public Property IDFolio As Integer
    Public Property IDGimnasio As Nullable(Of Integer)
    Public Property IDGimnasio2 As Nullable(Of Integer)
    Public Property IDCausante As Nullable(Of Integer)
    Public Property IDCliente As Nullable(Of Integer)
    Public Property IDProducto As Nullable(Of Integer)
    Public Property Cantidad As Nullable(Of Decimal)
    Public Property Precio As String
    Public Property Fecha As String
    Public Property Hora As String
    Public Property Iva As String
    Public Property Tipo As Nullable(Of Integer)
    Public Property Nuevo As Nullable(Of Integer)
    Public Property Enviado As Nullable(Of Integer)
    Public Property SerieFactura As String
    Public Property TipoCuota As Nullable(Of Integer)
    Public Property IDCliente2 As Nullable(Of Integer)

End Class
