'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblEvento
    Public Property IdEvento As Integer
    Public Property IdCliente As Nullable(Of Integer)
    Public Property IdGimnasio As Nullable(Of Integer)
    Public Property IdAcceso As Nullable(Of Integer)
    Public Property IdPuerta As Nullable(Of Integer)
    Public Property IdTipoEvento As Nullable(Of Integer)
    Public Property IdEstado As Nullable(Of Integer)
    Public Property IdFechaEvento As Nullable(Of Integer)
    Public Property FechaEvento As Nullable(Of Date)
    Public Property Procesado As Nullable(Of Integer)

End Class
