'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblEventosRapido
    Public Property IdEvento As Integer
    Public Property IdCliente As Integer
    Public Property IdGimnasio As Integer
    Public Property IdTipoEvento As String
    Public Property Atendido As String
    Public Property FechaAtencion As Nullable(Of Date)

End Class
