'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFoliosVenta
    Public Property IDFolio As Integer
    Public Property IDGimnasio As Nullable(Of Integer)
    Public Property IDGimnasio2 As Nullable(Of Integer)
    Public Property IDCausante As Integer
    Public Property IDCliente As Nullable(Of Integer)
    Public Property Fecha As String
    Public Property Hora As String
    Public Property Importe As String
    Public Property Tipo As Nullable(Of Integer)
    Public Property Pesos As String
    Public Property Dolares As String
    Public Property Cheque As Nullable(Of Integer)
    Public Property Tarjeta As Nullable(Of Integer)
    Public Property Cambio As String
    Public Property TipoCambio As String
    Public Property Nuevo As Nullable(Of Integer)
    Public Property IDUsuario As Nullable(Of Integer)
    Public Property Iva As String
    Public Property Estatus As Nullable(Of Integer)
    Public Property Enviado As Nullable(Of Integer)
    Public Property SerieFactura As String
    Public Property IDCliente2 As Nullable(Of Integer)

End Class
