'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblMovimientoCaja
    Public Property IDmovimiento As Integer
    Public Property IDUsuario As Integer
    Public Property Monto_Movimiento As String
    Public Property Tipo_Movimiento As Integer
    Public Property Corte_Movimiento As Nullable(Of Integer)
    Public Property Concepto_Movimiento As String
    Public Property Comentario_Movimiento As String
    Public Property Solicito_Movimiento As String
    Public Property Fecha_Movimiento As String
    Public Property Hora_Movimiento As String
    Public Property AutorizadoPor_Movimiento As String
    Public Property Recibio_Movimiento As String

End Class
