'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProductoPrecio
    Public Property IDProducto As Integer
    Public Property IDZonaGeo As Nullable(Of Integer)
    Public Property Precio As Decimal
    Public Property IDGimnasio As Integer
    Public Property Precio2 As Nullable(Of Decimal)

End Class
