'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_AsistXHora
    Public Property CantSexo As Nullable(Of Integer)
    Public Property Sexo As Nullable(Of Integer)
    Public Property Fecha As String
    Public Property IDGimnasio As Integer
    Public Property Lunes As Nullable(Of Integer)
    Public Property Martes As Nullable(Of Integer)
    Public Property Miercoles As Nullable(Of Integer)
    Public Property Jueves As Nullable(Of Integer)
    Public Property Viernes As Nullable(Of Integer)
    Public Property Sabado As Nullable(Of Integer)
    Public Property Domingo As Nullable(Of Integer)
    Public Property Hora As String

End Class
