'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_Asistencia
    Public Property Nombre As String
    Public Property Hora As String
    Public Property IDCliente As Integer
    Public Property Sexo As Nullable(Of Integer)
    Public Property IDGimnasio As Integer
    Public Property Fecha As String
    Public Property IDGimnasio2 As Integer

End Class
