'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_AsisVencidas
    Public Property Asistencia As Nullable(Of Integer)
    Public Property FechaVencimiento As String
    Public Property FechaUltimaAsistencia As String
    Public Property IDCliente As Integer
    Public Property Nombre As String
    Public Property Telefono As String
    Public Property FechaAlta As String

End Class
