'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_ComprasXProducto
    Public Property Compras As Nullable(Of Decimal)
    Public Property Descripcion As String
    Public Property IDGimnasio As Nullable(Of Integer)
    Public Property IDproducto As Nullable(Of Integer)
    Public Property IDTipo As Integer
    Public Property FechaInvFisico As String
    Public Property Fecha As String
    Public Property TipoMovimiento As String
    Public Property Cantidad As Nullable(Of Decimal)
    Public Property Procesada As Nullable(Of Integer)

End Class
