'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_Empleados
    Public Property IDEmpleado As Integer
    Public Property NombreCompleto As String
    Public Property Estatus As Integer
    Public Property Direccion As String
    Public Property IDColonia As Nullable(Of Integer)
    Public Property Municipio As String
    Public Property Localidad As String
    Public Property CPostal As String
    Public Property FechaNacimiento As String
    Public Property FechaAlta As String
    Public Property Telefono As String
    Public Property Movil As String
    Public Property NombreUsuario As String
    Public Property Contrasena As String
    Public Property IDGimnasio As Integer
    Public Property IDCausante As Nullable(Of Integer)
    Public Property NivelUsaurio As Nullable(Of Integer)
    Public Property IDMunicipio As Nullable(Of Integer)
    Public Property DentroSistema As Nullable(Of Integer)
    Public Property eMail As String
    Public Property Gimnasio As String
    Public Property Minicipio As String

End Class
