'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_FolioDesgloceGimnasio
    Public Property IDFolio As Integer
    Public Property Importe As String
    Public Property Hora As String
    Public Property Estatus As Nullable(Of Integer)
    Public Property Fecha As String
    Public Property Tarjeta As Nullable(Of Integer)
    Public Property IDGimnasio As Nullable(Of Integer)
    Public Property RazonSocial As String
    Public Property Nombre As String
    Public Property IDCausante As Integer
    Public Property IDTipo As Integer
    Public Property Precio As String
    Public Property Cantidad As Nullable(Of Decimal)
    Public Property Descripcion As String
    Public Property SerieFactura As String

End Class
