'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_Test
    Public Property Cantidad As Nullable(Of Integer)
    Public Property IDCliente As Integer
    Public Property Maxx As String
    Public Property Minn As String
    Public Property IDGimnasio As Integer
    Public Property Nombre As String
    Public Property FechaAlta As String
    Public Property Sexo As Nullable(Of Integer)
    Public Property Ocup As String
    Public Property Fecha As String

End Class
