'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_VentasxProdHist
    Public Property IDFolio As Integer
    Public Property IDProducto As Nullable(Of Integer)
    Public Property Cantidad As Nullable(Of Decimal)
    Public Property Fecha As String
    Public Property Estatus As Nullable(Of Integer)

End Class
